apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gpu-deploy-00
  name: gpu-deploy-00
  namespace: pai-gpu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpu-deploy-00
  template:
    metadata:
      labels:
        app: gpu-deploy-00
    spec:
      containers:
      - image: tensorflow:latest
        name: main
        resources:
          limits:
            alibabacloud.com/gpu-mem: 1024Mi
            alibabacloud.com/gpu-count: 1
            cpu: 4
            memory: 9216Mi
          requests:
            alibabacloud.com/gpu-mem: 1024Mi
            alibabacloud.com/gpu-count: 1
            cpu: 4
            memory: 9216Mi
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
